### ISSUE TITLE
[Request] Add ability to disconnect when switching PSU off

### ISSUE THREAD

**Issue by Kunsi** [kantlivelong/OctoPrint-PSUControl#10]
My PSU does also supply power to the printers mainboard. That means octoprint will display 'connection timeout' when PSU switches off, and i have to manually reconnect when switching PSU on.

It would be nice if your plugin would handle that as well, including an (ideally configurable) delay between 'PSU On' and 'reconnect to printer' to allow firmware to boot up.

**Comment by kantlivelong** [comment]
Have you considered trying [PortLister](http://plugins.octoprint.org/plugins/portlister/)?

**Comment by Kunsi** [comment]
That indeed would solve the issue when powering on, yet still would result in a connection timeout when PSU switches off.

**Comment by kantlivelong** [comment]
I'll see if it's something I can add in the future.

If you are using an ATX supply I would recommend connecting the printer PCB & Pi to your +5VSB if possible.

**Comment by Kunsi** [comment]
I indeed use an ATX supply. However the Microcontroller on the printers PCB is powered by an voltage regulator, which is powered by the 12V rail of the printer - so no way to fix that without changing electronics.

**Comment by Kunsi** [comment]
disconnecting should be possible with calling `self._printer.disconnect()` before actually switching off in https://github.com/kantlivelong/OctoPrint-PSUControl/blob/master/octoprint_psucontrol/__init__.py#L267

**Comment by kantlivelong** [comment]
Available in 0.1.4
