### ISSUE TITLE
PSU control interrupted an active print 

### ISSUE THREAD

**Issue by svh1985** [kantlivelong/OctoPrint-PSUControl#104]
#### What were you doing?
I've just installed PSU control and I've setup the timeout to 15mins.
My first print after installed PSU control the print got interrupted by the printer being off.
When I investigated I found out in the logs that PSU control turned off the printer.

#### What did you expect to happen?
I've expected the printer to be turned off after the print finished.
#### What happened instead?
The print got interrupted by a power off.
#### Version of OctoPrint-PSUControl

Latest

#### Operating System running OctoPrint

OctoPi 0.15

#### Printer model & used firmware incl. version

Ultimaker 2+

#### Link to octoprint.log with octoprnt.plugins.psucontrol set to DEBUG
Debug mode was off, I have to print something with DEBUG on. Give me a few days.

#### Wiring diagram

![aansluiting printer relay_schema](https://user-images.githubusercontent.com/5213210/39863068-dc7c9f56-5445-11e8-8b22-9057caeba22a.png)

**Comment by kantlivelong** [comment]
Please fill out missing info in the issue template. See https://github.com/kantlivelong/OctoPrint-PSUControl/blob/master/.github/ISSUE_TEMPLATE.md
