### ISSUE TITLE
[Request] Variable to delay between polls when using system command for sensing

### ISSUE THREAD

**Issue by tech-rat** [kantlivelong/OctoPrint-PSUControl#108]
Please add a variable for the delay between polling cycles when using a system command for sensing.

Line 367 in __init__.py = self._check_psu_state_event.wait(5)
Is hard coded to 5 seconds.

My setup I am SNMP polling a network attached power strip and feel that was TOO frequent.
I changed it to 30 sec but thought if it was a variable then it won't break on upgrades.

Thanks
Tech-Rat

**Comment by kantlivelong** [comment]
I agree it should be added. Though I'm not sure if there should be a min/max limit in the UI.

**Comment by kantlivelong** [comment]
Added to devel. Will be in 0.1.9

**Comment by kantlivelong** [comment]
This was released (a while ago!)

**Comment by tech-rat** [comment]
Yes it was. Works great.

Todd
