### ISSUE TITLE
[Request] Add checkbox for internal pullup/pulldown

### ISSUE THREAD

**Issue by Kunsi** [kantlivelong/OctoPrint-PSUControl#11]
It should be possible to switch on the internal pullup/pulldown-resistors, which would allow for direct wiring of ATX PSUs.

**Comment by kantlivelong** [comment]
Only pins configured as an input support pull up/down. What you are looking for is **open drain**. which the Raspberry Pi does not support.

To switch on an ATX supply via GPIO use a standard NPN transistor.

See [Using the Raspberry Pi to control an ATX power supply](http://www.instructables.com/id/Using-the-Raspberry-Pi-to-control-an-ATX-power-sup/)

**Comment by Kunsi** [comment]
Yeah, also figured ATX PSUs do have an internal pullup to 3V3, so it should be possible to connect the PSU directly to GPIO.
