### ISSUE TITLE
missing schematic in wiki

### ISSUE THREAD

**Issue by nionio6915** [kantlivelong/OctoPrint-PSUControl#110]
https://github.com/kantlivelong/OctoPrint-PSUControl/wiki/Wiring-Diagrams

The image of the "All There" wiring diagram is missing. 

Can it be recovered?

![image](https://user-images.githubusercontent.com/17693150/43463144-8a3f0b96-949d-11e8-8d47-71c6e5d883c1.png)

**Comment by mad2xlc** [comment]
Anything new on this?

**Comment by nionio6915** [comment]
I dug this up from my notes. I offer no guarantee on accuracy. 

![file](https://user-images.githubusercontent.com/17693150/53789156-6b4cad00-3ee9-11e9-91ff-6507a270b634.png)

svg in the zip file b/c git no likey the extension. 

[file.zip](https://github.com/kantlivelong/OctoPrint-PSUControl/files/2929834/file.zip)

**Comment by SysGh-st** [comment]
> I dug this up from my notes. I offer no guarantee on accuracy.
> 
> ![file](https://user-images.githubusercontent.com/17693150/53789156-6b4cad00-3ee9-11e9-91ff-6507a270b634.png)
> 
> svg in the zip file b/c git no likey the extension.
> 
> [file.zip](https://github.com/kantlivelong/OctoPrint-PSUControl/files/2929834/file.zip)

Neat. But keep in mind that most ATX supplies have a rather weak 5VSB (5V, StandBy) supply around a few hundred milliamps to about an ampere at best. Far from enough for a Raspberry Pi. Might work at first, but will burn out the 5VSB supplying IC/regulator prematurely.

**Comment by kantlivelong** [comment]
Decided to remove schematics for now.
