### ISSUE TITLE
Working on pc1 not pc2

### ISSUE THREAD

**Issue by Spyder19** [kantlivelong/OctoPrint-PSUControl#111]
#### What were you doing?
Rebooting Octoprint

1. ...Reboot Octoprint, or have the printer in a power down state
2. ...From computer #1, click on the little red lightening bolt that indicates that the printer is in a power down state, indicating that I wish it to be in a power up state
3. ...The little red lightening bolt stays red, indicating that it did not enter a power up state
4. ... Go to computer #2, using the same credentials, on the same network, and click on the little red lightening bolt, and the little red lightening bolt turns green, indicating that the printer has entered a power on state, while visually verifying that the printer has indeed entered a power on state, with a double verification due to the lights coming on, the screen lighting up, and Octoprint being able to connect

#### Version of OctoPrint-PSUControl
0.1.7

#### Operating System running OctoPrint
Octoprint 1.3.9 running on Octopi 0.15.1

Client computers were both running win7, using Chrome v67. The one that doesn't work is 32bit, and the one that does is 64bit

#### Printer model & used firmware incl. version
Anet A8 printer running ANET_A8_20160525 firmware

#### Link to octoprint.log with octoprnt.plugins.psucontrol set to DEBUG
https://pastebin.com/PNDXCWx5

**Comment by kantlivelong** [comment]
Hi @Spyder19 ,

Looking at the logs it looks as if debug is not set on. Aside from that, are you using authentication? If so, are you authenticated on both machines?

**Comment by Spyder19** [comment]
I checked the logging page, and it looked like it was set to debug, so I added error to it just in case maybe it didn't stick or something

And yes, I saw the 403 error, but I'm logged in with the proper credentials. I have access control turned on, and have full control. In fact, it gets even stranger, I just found out that I can turn it OFF from that computer, it's just that ON doesn't work. 

I need to turn off the octoprint anywhere cuz I got a note from the author saying that I had more than one printer, so he wanted to start billing me. I deleted that printer from the online account, but forgot to deactivate the plugin, so, you can ignore those errors

**Comment by kantlivelong** [comment]
Make sure plugins.octoprint.psucontrol is set to DEBUG then restart OctoPrint, retest, and upload logs.

**Comment by Spyder19** [comment]
Long print going on right now. Will do that when it's finished
