### ISSUE TITLE
Support orange pi lite and orange pi family

### ISSUE THREAD

**Issue by userosos** [kantlivelong/OctoPrint-PSUControl#115]
Hi! Can you add support orange pi lite in the plugin. I install it and i can not see GPIO Mode - BCM. 
I use the manual:
https://diyprojects.io/orange-pi-armbian-install-wiringop-library-wiringpi-equivalent/
But my ssr not work (The ssr work ok if i connect to +5 V and gnd) with the library.

**Comment by kantlivelong** [comment]
Hi @userosos,

I will be looking into adding SysFS support which should support most devices with GPIO.

**Comment by jypma** [comment]
Interested in this as well, but here's a workaround until then (tested on my OrangePi One):
(assuming GPIO 4 and 5 here for output / sense, but you can change that to what you like)

- Install [WiringOP](https://diyprojects.io/orange-pi-armbian-install-wiringop-library-wiringpi-equivalent/)
- Edit `/etc/default/octoprint` to have the following extra lines:
```
gpio mode 4 out
gpio mode 5 in
```
(yeah, there's probably a better place for those, but OK)
- In the Octoprint plugin configuration for PSU, set _On system command_ to `/usr/local/bin/gpio write 4 on`, set _Off system command_ to `/usr/local/bin/gpio write 4 off`, and set _Sense system command_ to `! /bin/bash -c 'exit $(/usr/local/bin/gpio read 5)'`

(I'm controlling an ATX PSU from the Orange Pi One)

**Comment by RaptorHunterMZ** [comment]
>     * /etc/default/octoprint

I can't find that directory can you help?

**Comment by kantlivelong** [comment]
If anyone is interest I have a [WIP branch](https://github.com/kantlivelong/OctoPrint-PSUControl/tree/periphery_gpio) that uses Periphery which supports GPIO through the dev interface.  

There are quirks when changing settings but otherwise seems to be working. If you're interested give it a go and shoot some feedback.

**Comment by kantlivelong** [comment]
27e66a2 in devel brings in Periphery support and yanks out RPi.GPIO. Not released yet but expect it to come.

**Comment by kantlivelong** [comment]
v1.0.0 released.
