### ISSUE TITLE
Installing the same plug-in 2 times

### ISSUE THREAD

**Issue by mlassota76** [kantlivelong/OctoPrint-PSUControl#116]
Hello.

Is it possible to install the same plug-in 2 times?
I mean exactly PSU Control I have it installed and configured to control the power supply via G-code.
In another configuration, it allows you to control the power supply via the Rapbspberry pins
Is it possible to install the same plug-in twice and configure it differently

I will be grateful for the information and if it is possible to indicate how to perform the described operation. Regards

**Comment by kantlivelong** [comment]
OctoPrint only allows one plugin instance at a time. You could pull down the source and rename all identifiers.
