### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by azalanono** [kantlivelong/OctoPrint-PSUControl#12]
Hello Shawn Bruce,
first, this PSU control is really excellent and very helpful.  
My PSU is permanently on, I use the ATX power control output as an additional output for turning cooling fans on/off to reduce noise in idle mode. Here does your PSU control wonderful things.

What I want to request is a little extension to PSU control. It is some kind of safety agains overheating.
You currently have implemented that PSU control can turn the PSU off only when the temperature(s?) are below a configured level. -> Excellent!
**What I miss is an option to _enforce a turned-on PSU_ as long as that limit is exceeded!**

Background:  
I had it several times that I had to reset the Arduino or OctoPi. In this case it happens that the Arduino (Marlin Firmware) defaults to a turned off PSU. This causes in turn that a heated up hotend is not cooled any more and needs very long to get an uncritical temperature.
In case that you would add a trigger to turn on the PSU when the temperature is higher than ...°C, it would be perfect.

**Comment by kantlivelong** [comment]
This seems more like a firmware issue that should be addressed.
