### ISSUE TITLE
Power On/Off control

### ISSUE THREAD

**Issue by kotuk** [kantlivelong/OctoPrint-PSUControl#123]
I have Lerdge board and lerdge power monitoring relay.
mine issue is:
Powers ON ok via GPIO but sometimes don't want to power off.
i thought that enabling GPIO and G-Code will fix my issue, but it not as i found that it Pseudo and it not sending M81 signal together with GPIO.

Is it possible to make that GPIO and normal G-Code was sent when power off (i understand that changing relay fix my problem) but i want to run with this relay that i already have.

**Comment by kantlivelong** [comment]
Sorry but this is a hardware implementation problem.
