### ISSUE TITLE
GCode PSU Shutdown fails

### ISSUE THREAD

**Issue by milmber** [kantlivelong/OctoPrint-PSUControl#128]
Shutting down my Ender 3 Pro (Vanilla Marlin 1.1.6 - no upgrades) connected via USB only to Octoprint Version 1.3.10 running on a Pi 3B+ seems to fail.

I get the following GCode output however the Ender PSU fans keep on spinning.

`Send: M81
Recv: File(bin) deleted.`

Octoprint logs below doesn't seem to indicate an obvious error:
`2019-05-12 10:45:37,694 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature`
`2019-05-12 10:45:53,776 - octoprint.plugins.psucontrol - INFO - Switching PSU On`
`2019-05-12 10:46:03,610 - octoprint.plugins.psucontrol - INFO - Switching PSU Off`
`2019-05-12 10:46:07,745 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature`

My expectation (perhaps incorrectly) was that using this plugin would mimic switching off the PSU using the PSU power switch?

Plugin Configuration Below:

![PSUControl Config](https://user-images.githubusercontent.com/7280701/57580699-d47e0d00-74a4-11e9-92f5-a16ee5dd5e49.png)

**Comment by kantlivelong** [comment]
Doesn't look like your pcb supports it M80/M81 or it's an different command.
