### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by chrstrvs** [kantlivelong/OctoPrint-PSUControl#130]
Hi!

I would like to be able to use a G-Code command and a GPIO pin to toggle my PSU. Would that be possible to implement?

Regards,
Christian

**Comment by nionio6915** [comment]
Did you read the docs? 
M80 and M81 are already in there for this exact purpose.

**Comment by chrstrvs** [comment]
Oh wait, I thought that one of the methods of switching was using a input pin to toggle a output pin, but I see now that is not the case.
What I wanted was to be able to switch a output pin using either G-Code or a input pin.

**Comment by kantlivelong** [comment]
O_O
