### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by SchmidtPhilipp** [kantlivelong/OctoPrint-PSUControl#132]
Hi, 

the last days i was tring to hack a remote Socket Relais to be used with your PSU control, i got it from an local store and after opening with out any digging deeper in the circuit i noticed that it puls one of two lines to 3.3v depending on which Button is pushed on the remote. 

I thought if it is maybe possible to have a Gpio Pin for an enable and one pin for the dissable command both being able to be configured with an pulse of customizable length. 

Unfortunately all ICs in the remote lack their branding so diggin deeper in the circuit is really time consuming. 

Thanks Br

**Comment by kantlivelong** [comment]
Nothing I can really do here but sub-plugins are now supported in devel 27e66a21e91cfb855bf1b78006c16cbd0cedd632.
