### ISSUE TITLE
Possible to make GPIO pin timed ? 

### ISSUE THREAD

**Issue by chmadkk** [kantlivelong/OctoPrint-PSUControl#14]
Hi.

Im trying to control the power of my Solidoodle Press. 
And the problem is that the printer is controlled by a power switch on the top. 
It would be great if the plugin could handle lets say. power on = GPIO high 2 sec And then low again. 
To switch power on off.

**Comment by kantlivelong** [comment]
I think this would be a bit out of scope of the plugin as it is primarily designed to switch on an ATX/AUX power source while the printer PCB is always on. 

You can still achieve what your looking for by using Command based switching that calls a custom script/program.
