### ISSUE TITLE
Swithing On RPi4 working ?

### ISSUE THREAD

**Issue by arut16** [kantlivelong/OctoPrint-PSUControl#145]
#### What did you expect to happen?

Relay Openning/Closing by control button in octoprint Bar

#### What happened instead?

Nothing ! Reley remain open everytime.

#### Version of OctoPrint-PSUControl

![image](https://user-images.githubusercontent.com/58274805/81338175-7599a680-90ac-11ea-8c90-159a12b016f7.png)

#### Operating System running OctoPrint

OctoPi Version 1.4.0
Octoprint, Version 0.17.0, running on Raspberry Pi 4 Model B Rev 1.1

#### Printer model & used firmware incl. version

Ender 3 Pro with SKR 1.3 and Marlin 2.0.5.3

#### Link to octoprint.log with octoprnt.plugins.psucontrol set to DEBUG

https://gist.github.com/arut16/d2f934afa5e332d664a8552556a7faf9

#### Wiring diagram
![image](https://user-images.githubusercontent.com/58274805/81338922-b0500e80-90ad-11ea-9990-6783ff2153c6.png)

**Comment by kantlivelong** [comment]
I don't have one to test unfortunately. Doesn't look like debugging was enabled for psucontrol in your logs either.

Is the mode set correctly?
Did you test the GPIO pin with a multimeter?

**Comment by arut16** [comment]
Solved : I tried with 3.3V on PiN 1 and it starts to work! Very strange. Normally my Tongling JQC-3FF-S-Z (very common relay) is 5V logical...

![15888852384357384685125439507151](https://user-images.githubusercontent.com/58274805/81344211-a383e880-90b6-11ea-98bc-4b74ca606b4a.jpg)
