### ISSUE TITLE
[Request] Make confirmation of switching off optional

### ISSUE THREAD

**Issue by Kunsi** [kantlivelong/OctoPrint-PSUControl#15]
Hi,

there should be an option to disable "Are you sure" confirmation when switching off the PSU.

Best would be a select option, choosable between:
- Always ask
- Never ask
- Only ask if criteria for "automatic power off" is not met

**Comment by kantlivelong** [comment]
Added to devel

**Comment by kantlivelong** [comment]
Available in 0.1.4
