### ISSUE TITLE
[Request] Add custom permission for PSUControl

### ISSUE THREAD

**Issue by jara001** [kantlivelong/OctoPrint-PSUControl#150]
Hello!
With the latest version of Octoprint, it should be possible to create custom permissions. It would be nice to have a separate PSUControl permission and not just rely on 'all users'.

J.

**Comment by kantlivelong** [comment]
Hi @jara001 

So with the existing legacy permissions any valid user is able to turn power on & off. Anonymous users can view the status.

So I think the proposed changes would be to only allow switching if the user has either Print or Control rights. Should not need to implement any new permissions for this.

**Comment by kantlivelong** [comment]
v1.0.0 brings in support for the newer OctoPrint Access Control.
