### ISSUE TITLE
Sensing on same pin?

### ISSUE THREAD

**Issue by MarMed** [kantlivelong/OctoPrint-PSUControl#16]
I'm using an enclosed relay,  [this](https://www.amazon.com/Iot-Relay-Enclosed-High-power-Raspberry/dp/B00WV7GMA2/ref=sr_1_1?ie=UTF8&qid=1489041076&sr=8-1-spons&keywords=iot+relay&psc=1) specifically. How advisable or inadvisable would it be to use the same pin for switching and sensing? My hopeful educated guess is that it would be better than using last action.

**Comment by kantlivelong** [comment]
Sensing should be connected to the output voltage of the power source that's being switched on.

If you are using that to switch on a 12V supply then connect the sensing wire to the 12V output of the supply (Use a voltage divider)

See [GPIO Setup:Sensing](https://github.com/kantlivelong/OctoPrint-PSUControl#sense-gpio-pin)
