### ISSUE TITLE
Interferrence by another plugin 

### ISSUE THREAD

**Issue by jtannenba** [kantlivelong/OctoPrint-PSUControl#161]
Don't know if this is a problem or just miscommunication of documentation.  Have PSU set up and working just fine, then added the smart filament plugin and a sensor, now psu won't work.  the Pi doesn't toggle, it appears it floats.  The relay I'm using requires a low to turn off.  Both plugins are set to BOARD and PSU is on pin 12 the filament sensor is on 11.  If I disable the filament sensor, psu works again.  Should I set one or the other to different pins?

**Comment by ChristianH99** [comment]
You find a solution here:
[https://github.com/maocypher/Octoprint-Smart-Filament-Sensor/issues/31](url)
