### ISSUE TITLE
New Wiki page to have the printer autoconnect on power on...

### ISSUE THREAD

**Issue by MSLaaf** [kantlivelong/OctoPrint-PSUControl#169]
[AutoConnect.zip](https://github.com/kantlivelong/OctoPrint-PSUControl/files/5961313/AutoConnect.zip)
There is a great description to have a raspberry pi (and likely any other code) automatically do a printer connect when the power gets turned on - and the serial port appears. I have an Ender 3 with a EZLite control board, but the process documented on the webpage works:
WIKI FILE: AutoConnect.md
`## Automatic Printer reconnect on

Bernd Zeimetz wrote a great article to setup a mechanism to automatically connect a printer

[Connecting your 3D printer to OctoPrint automatically](https://bzed.de/post/2017/11/octoprint_autoconnect_printer/)
`
I attached the file because it's not trivial to fork the wiki...

**Comment by kantlivelong** [comment]
Autoconnect is already possible via the PortLister plugin and this plugin will attempt to connect as well if turned on. Not sure what this even has to do with the plugin.
