### ISSUE TITLE
Is it possible to use the power good wire (grey) for the sense gpis pin?

### ISSUE THREAD

**Issue by mok-liee** [kantlivelong/OctoPrint-PSUControl#17]
Hi, i have already cut of my 3v3 sense wire and solder it to a 3v3 wire. Then I see ur plugin.

can I use also the 5v power good wire?

greetings mok

**Comment by kantlivelong** [comment]
You can use sensing on any output voltage from your switched power supply provided you make sure the raspberry pi only received a 3.3v signal. Typically use a voltage divider.
