### ISSUE TITLE
Feature Request to shutdown RPi

### ISSUE THREAD

**Issue by empakoso** [kantlivelong/OctoPrint-PSUControl#170]
Here is another way I use this plugin.  I have limited coding experience so I wrote a python script that uses this plugin's output.  It reacts by shutting down the RPi gracefully and causes the "release" of a relay that holds the power on to the 3D printer and RPi.

The key to my request is a shutdown feature (to replace my bulky "python-addon" script)  in the pulldown list.

The other plugins that control power receptacles do not have this "graceful" RPi shutdown feature.  This idea does it with a bit more security, by ensuring physical presence to power ON.  The idea comes from a typical motor starter circuit every electrician can sketch in their sleep!

The principle function is that a relay is turned on using the RPI serial TX function aka GPIO pin7 when the RPI is running.  This holds the relay ON and keeps everything powered-up.

To achieve this:
1. PSU plugin activates this "shutdown"
2. RPi gracefully shuts down (first shutting down the daemon)
3. GPIO Serial TX pin7 is released only after RPi is completely off
3. A relay opens contacts which provide 110VAC to power supply
4. A push button is momentarily held closed across the relay's NO contacts to power everything ON

What needs to happen for this all to work:
1. A relay's NO contacts wired between the printer PSU's 110VAC hot terminal and the power cord
2. NO open push button is wired across these NO relay terminals
3. This relay is power ON using GPIO pin7 (RPi is configured with Serial comms turned ON)
4. Buck power supply is wired from same PSU to power (5v 2A) RPi

As additional helpful features:
a) A toggle from 3.3v pin to "hold" the relay when doing OctoPrint upgrades requiring reboots (requires diode)
b) If a person who is not handy with OctoPrint needs to gracefully shut down; another push button input is detected
c) Shutdown is delayed if this toggle is ON by detecting this condition using another GPIO pin wired between the toggle and relay (requires diode)

Thank you for your consideration.

**Comment by kantlivelong** [comment]
Sorry but this is too specific of a use case and I'm not encouraging anyone to do anything with mains wiring/voltage.
