### ISSUE TITLE
WIP - add helpers and event to plugin

### ISSUE THREAD

**Issue by edekeijzer** [kantlivelong/OctoPrint-PSUControl#174]
I have tried adding these before a few months ago, but without any reaction so now I've ported my modifications to the current codebase and I'd like to know what would be the right way to get them merged into your plugin.
The _helpers_ branch in [my fork](https://github.com/edekeijzer/OctoPrint-PSUControl/tree/helpers) adds an event and some helpers (turn_psu_on and turn_psu_off and a new function, get_psu_state) which allows other plugins to interact with PSUControl.
I have tested this with some modifications I did to the [Home Assistant plugin](https://github.com/edekeijzer/OctoPrint-HomeAssistant/tree/psucontrol), which allows me to control the printer PSU from my home automation system.
Please let me know if I could be of any help testing this, I could set up a virtual test environment in Docker with both plugins installed.

**Comment by kantlivelong** [comment]
Hi @edekeijzer,

Sorry hadn't gotten back to you. I was actually working on a local branch for helpers back in Feb 2020 but never continued it. I'm a little slow with PRs. 

I think adding helpers would be helpful(heh). Though I think it would be beneficial to have a setting that is defaulted to off for allowing on/off/toggle through helpers. IE "Allow other plugins to switch power on/off".

I've pushed the branch I was working on to https://github.com/kantlivelong/OctoPrint-PSUControl/tree/octoprint_helpers so you can get an idea of what I was doing. My development process usually goes through a few iterations before I merge to dev and eventually master. 

I was also looking into allowing other plugins to register themselves as switching and sensing methods. The idea was to have them register through a helper then have the user select in the dropdown.

As for custom events, no issue there. I suppose they would be something like `PowerOn`, `PowerOff` but don't quote me on the names.

PS: I'm usually on the OctoPrint Discord - https://discord.octoprint.org/

**Comment by edekeijzer** [comment]
I've created a PR for this one, had a quick look at your octoprint_helpers branch which looks good but seems to be based on some older version of the plug-in so it'll probably need some backporting.

**Comment by kantlivelong** [comment]
v1.0.0 released.
