### ISSUE TITLE
PSU no longer works after update

### ISSUE THREAD

**Issue by htrabbit** [kantlivelong/OctoPrint-PSUControl#190]
#### What were you doing?

1. ...turn on Pi 4 
2. ...on the octopint webpage select the lightening bolt to turn on printer
3. ...printer does not turn on (worked before update)
4. ... i turned on psuplugin debug but no log file is generated

#### Operating System running OctoPrint
octopi on linux

#### Wiring diagram
i am using pin 40 to trigger a ssr
![PSU-Term](https://user-images.githubusercontent.com/59135057/115128254-4fa1a500-9f91-11eb-94bb-4de7a4b804ad.png)
![PSU-Term2](https://user-images.githubusercontent.com/59135057/115128259-54feef80-9f91-11eb-9ef6-ddae5040ae48.png)
![PSU-Term3](https://user-images.githubusercontent.com/59135057/115128261-57f9e000-9f91-11eb-84f3-d5ef13e15ea2.png)
the above term window after i issue an M80 Command
![PSU-Term4](https://user-images.githubusercontent.com/59135057/115128354-21709500-9f92-11eb-9145-72ea747b72a0.png)
[PSUlogs.zip](https://github.com/kantlivelong/OctoPrint-PSUControl/files/6330143/PSUlogs.zip)

**Comment by kantlivelong** [comment]
40? Do you mean to use GPIO21?

**Comment by gallowayk** [comment]
Same thing... PSU control just refuses to work for me, though I was forced to use the RPi GPIO "sub-plugin". Even when configuring it the same way, the plugin doesn't function correctly or at all.

**Comment by kantlivelong** [comment]
restart OctoPrint atter making changes to PSUControl-RPi.GPIO. will need debug logs with the correct pin number for this plugin to continue

**Comment by htrabbit** [comment]
pin 40 is GPIO21 thats correct
should i change it to 21???
it has always been set as 40

**Comment by htrabbit** [comment]
should i set PSUControl to zero's and use only the PSUControl-RPi.GPIO set to 21?

**Comment by htrabbit** [comment]
2021-04-18 00:50:08,875 - octoprint.plugins.psucontrol_rpigpio - ERROR - You must setup() the GPIO channel first
2021-04-18 00:50:08,875 - octoprint.plugins.psucontrol - DEBUG - isPSUOn: False

**Comment by htrabbit** [comment]
OK i have it working, It appears that PSUcontrol-rpigpio is not necessary for me at least
1. uninstall psucontrol_rpigpio
2. 
![PSU-setting3](https://user-images.githubusercontent.com/59135057/115129975-0b69d100-9fa0-11eb-8e7e-cc95260dd3b6.png)

**Comment by kantlivelong** [comment]
That's it. Closing

**Comment by htrabbit** [comment]
A BIG  thank you 
this was fast response.

**Comment by kantlivelong** [comment]
All good
