### ISSUE TITLE
Can't toogle power icon and print issues

### ISSUE THREAD

**Issue by rodrigomdamaia** [kantlivelong/OctoPrint-PSUControl#194]
Hey guys

after installing version 1.0.2 the on button only turns on the printer, however it does not change the status and it is not possible to turn off, the plugin affected the printing of circles and ellipses, after removing the plugin the printing problem disappears.

**Comment by kantlivelong** [comment]
Fill out the required info for new tickets.

**Comment by 3dmadnessnl** [comment]
where can i vind the old app

**Comment by kantlivelong** [comment]
@rodrigomdamaia open a new ticket providing all required info in the template. Closing this one.
