### ISSUE TITLE
PSU button does not toggle anymore

### ISSUE THREAD

**Issue by mirco71** [kantlivelong/OctoPrint-PSUControl#196]
After the update to 1.0.2 the button located in the top bar does not work anymore. PSU control is used only to switch on/off the printer via this button. Before the update the button was working well.  Now, the button does only change its color.

**Comment by DisasteR** [comment]
same here

**Comment by DeC1pher** [comment]
Same here... please fix asap

**Comment by plangenh** [comment]
same here

**Comment by wutwiesel** [comment]
Same issue here. Switching mode set to GPIO but in the top most dropdown the `BCM` entry isn't showing up, only `/dev/gpiochip0`
