### ISSUE TITLE
PSU button does not toggle anymore 2

### ISSUE THREAD

**Issue by degg** [kantlivelong/OctoPrint-PSUControl#197]
Why hide https://github.com/kantlivelong/OctoPrint-PSUControl/issues/196 ?
Somewhere Board & BCM for "On/Off GPIO Pin" seems to be switched after the update.

Switching the pin to BCM will probably fix it (for now?).

**Comment by kantlivelong** [comment]
Because the ticket did not provide the required info. The fact that I am telling you now confirms that you also did not read the template. Open a valid ticket with useful info.
