### ISSUE TITLE
[Request] Delay to connect when powered on

### ISSUE THREAD

**Issue by tfurci** [kantlivelong/OctoPrint-PSUControl#207]
Would it be possible to add customizable time delay when auto connecting when powered on?

**Comment by kantlivelong** [comment]
Are you referring to having a delay pre or post connect? What's the use case?

**Comment by tfurci** [comment]
Pre connect because it tries to connect immediately when i turn on printer but i usually have to wait around 10 seconds for printer to fully boot otherwise i get error.

**Comment by kantlivelong** [comment]
That would be the post on delay setting.

**Comment by kantlivelong** [comment]
I've updated the wiki to reflect this.
https://github.com/kantlivelong/OctoPrint-PSUControl/wiki/Settings

**Comment by kantlivelong** [comment]
Closing this for now but can reopen if necessary.
