### ISSUE TITLE
Triggering plugin from shell

### ISSUE THREAD

**Issue by Erutan409** [kantlivelong/OctoPrint-PSUControl#21]
Is there a way to do this?  Reason I ask is because I use Printoid (Android app to connect to OctoPrint) and I'd like to be able to use this plugin with it, by using the app's shell function capabilities.

**Comment by kantlivelong** [comment]
Not very familiar with Printoid. Does it just execute system commands on the OctoPrint system or do "shell functions" have some other meaning?

**Comment by Erutan409** [comment]
Executing commands from the shell.  So, basically via SSH.  I don't plan on implementing the sensing GPIO.  So, I'd want to coordinate on/off via your plugin and not worry about a state not being noticed, using the printer interchangeably from the web GUI to my Android app.

**Comment by Erutan409** [comment]
I could write a script that I could run against python from said app, but again - I don't want to lose track of its state based on the aforementioned.

**Comment by kantlivelong** [comment]
You can create a shell script that calls the API. 

Example with curl:
`curl -s -H "Content-Type: application/json" -H "X-Api-Key: YOUR_API_KEY" -X POST -d '{ "command":"turnPSUOn" }' http://YOUR_OCTOPRINT_SERVER/api/plugin/psucontrol`


Available API commands:
turnPSUOn
turnPSUOff

**Comment by Erutan409** [comment]
Awesome, thank you!

**Comment by kantlivelong** [comment]
No prob.
