### ISSUE TITLE
Plugins: HomeAssistant and Shelly

### ISSUE THREAD

**Issue by edekeijzer** [kantlivelong/OctoPrint-PSUControl#210]
Just to let you know, I really liked the plugin idea so I have created two plugins:
[OctoPrint-PSUControl-HomeAssistant](https://github.com/edekeijzer/OctoPrint-PSUControl-HomeAssistant): control a Home Assistant switch entity.
[OctoPrint-PSUControl-Shelly](https://github.com/edekeijzer/OctoPrint-PSUControl-Shelly): control a Shelly relay either directly or through Shelly Cloud.
Please note that while I did test them, these are just first versions and not yet released through the plugin repo. Any feedback is greatly appreciated on the plugin issue trackers.

**Comment by nibblerrick** [comment]
I just installed the shelly plugin and configured it with local connection and a shelly plug-S.
I took a quick look at the octoprint-logs and there wasn't anything, so it seems to work just fine.
Thanks both of you for this plugins, makes it really convenient :-)

**Comment by kantlivelong** [comment]
These were released.
