### ISSUE TITLE
More a question than an issue.. sorry about that..

### ISSUE THREAD

**Issue by Ruissilva** [kantlivelong/OctoPrint-PSUControl#211]
Do not seek support here ("I need help with ...", "I have a
What is the support page, i honestly don't know..

I have psu control working well, 0 issues. long live kantlivelong!! \m/ :P
I want to add a smoke sensor connected to the raspberry. If there is smoke, disconnects the printer. Is it possible to use psu control with this sensor? What is the best way?

Again, sorry about putting this question here.

**Comment by kantlivelong** [comment]
Hey @Ruissilva,

Not currently. You're best bet would be to create another plugin that makes use of helpers. However I urge you to re-consider going that route at all and instead use proper fire safety systems.
