### ISSUE TITLE
Toggle PSU not working since upgrade to OctoPrint 1.8.0

### ISSUE THREAD

**Issue by cjmorri1018** [kantlivelong/OctoPrint-PSUControl#239]
#### What were you doing? Attempting to adjust PSU Control and PSU - MQTT settings as had been installed just prior to upgrade to OctoPrint 1.8.0, and still being sorted.   

0. PSU Control & PSU - MQTT - Had been working, green toggle, communication with MQTT, MQTT capture setting changes, status changes, etc.  Working as expected
0.5  Updated to Octoprint 1.8.0
0.75 Issue reported with Octoprint 4a - Permissions to /dev,, developer patched moved to 1.1.0
 https://github.com/feelfreelinux/octo4a/issues/205#issuecomment-1129983790
1. ... I realized I had cleared out the codes in Power On Options --> Trigger commands without fully understanding and wanted them back..,  couldn't find a "restore defaults" so decided to uninstall/reinstall PSU Control in hopes they would populate on reinstall.  Noticed messages about "couldnt load settings files" with a couple of the restarts along the way below
2. ... Uninstalled PSU Control  & Reinstalled (did not "clean up data")- Power On Options --> Trigger Commands didn't reappear...so... 
3. .... Uninstalled PSU Control  & Reinstalled (with "clean up data") - Trigger commands came back - YAY!!
4. Adjusted a few settings in PSU Control - Test
5. PSU Control no longer toggles with lightning bolt no matter how hard I click (which did previously)
6. Adjusted a few settings in PSU Control and PSU Control - MQTT and tested
7. PSU Control no longer toggles with lightning bolt no matter how hard I click (which did previously)
8. Updating settings for PSU no longer reflects in MQTT (which did previously - had just been previously testing this just minutes before upgrade to OctoPrint 1.8.0)
9. Decided perhaps since I had un/reinstalled PSU without doing same for PSU-MQTT perhaps was a dependency or install out of order problem
10. Uninstalled both PSU Control and PSU MQTT, carefully, patiently with reboots in between
11.  Reinstalled PSU Control patiently, carefully with restart after
12. Took a quick look at PSU Control settings, didn't change anything - tried the toggle switch - no response, no green light/greyed out.
13. Reinstalled PSU Control - MQTT carefully and patiently with reboots in between
14. Configured PSU Control to use Plugin PSU Control - MQTT & Setup the PSU MQTT settings
15.  PSU Control toggle appears to have no effect
16. Adjusted a few settings in PSU Control and PSU Control - MQTT and tested
17. PSU Control toggle appears to have no effect
18. Updating settings for PSU no longer reflects in MQTT (which did previously - had just been previously testing this just minutes before upgrade to OctoPrint 1.8.0)

 N/A

#### Version of OctoPrint-PSUControl  

   - OctoPrint v1.8.0, PSU Control v1.0.6, PSU Control - MQTT v1.0.2 

#### Operating System running OctoPrint 

 - Linux, OctoPrint 4a 1.1.0, Android 10, Python 3.9.5

#### Printer model & used firmware incl. version

 Creality Ender 5 Pro - Marlin 1.1.1

#### Link to octoprint.log with octoprnt.plugins.psucontrol set to DEBUG

<script src="https://gist.github.com/cjmorri1018/2cd69df0ab14fa750fba39151c85155c.js"></script>
[octoprint-systeminfo-20220519143200.zip](https://github.com/kantlivelong/OctoPrint-PSUControl/files/8730412/octoprint-systeminfo-20220519143200.zip)

**Comment by kantlivelong** [comment]
You'll want to open a ticket with the PSUControl-MQTT repo as from what I can see the subplugin is returning None instead of a boolean value.

```
2022-05-19 14:30:24,527 - octoprint.plugins.psucontrol - DEBUG - Switching PSU On Using PLUGIN: psucontrol_mqtt
2022-05-19 14:30:24,646 - octoprint.plugins.psucontrol - DEBUG - Polling PSU state...
2022-05-19 14:30:24,648 - octoprint.plugins.psucontrol - DEBUG - isPSUOn: None
```

**Comment by cjmorri1018** [comment]
@kantlivelong - 

Thank you very much for the super quick response.  I will do this after I dig a bit more in case it is user error/settings,and will update my comments on the other issue.

**Comment by cjmorri1018** [comment]
I will just say VERY likely user error/settings..
