### ISSUE TITLE
[Suggestion] Auto shuttoff after print with delay, and auto connect after power with delay

### ISSUE THREAD

**Issue by light24bulbs** [kantlivelong/OctoPrint-PSUControl#24]
After power on I always have to manually connect.  It would be nice if the extension could configurably handle this on its own.  

Auto shutoff is something I think everyone wants.  I see "power off when idle" but the docs and configuration are very nonspecific about what idle means and it doesn't seem to turn my printer off automatically when finished printing.  Ideally this might happen after some configurable delay of me not initiating another print.. Maybe somewhere in the ten minute neighborhood in my case.  

If this is something that interests the lead on this project, I would be happy to try some implimentation and do a pull request.  Wanted to pitch the idea and see if I'm missing some prexisting or future planned feature first.

**Comment by kantlivelong** [comment]
Hello,

[PortLister](http://plugins.octoprint.org/plugins/portlister/) will automatically connect to your printer when the USB device becomes available.  

The plugin can automatically shut off your printer when idle for X minutes and the printer is considered idle based on the commands being sent over the connection. 

An option to turn the power off upon print completion is doable but I have not yet considered the way I would prefer it to be implemented. One way I've considered is to make psuedo gcode commands available for those not using gcode(M80/M81) to switch power. This way they can be done in gcode scripts.
