### ISSUE TITLE
Unable to connect to the printer

### ISSUE THREAD

**Issue by Autro** [kantlivelong/OctoPrint-PSUControl#29]
Once I flip the switch on PSU raspberry pi comes to life and loads the system. Meanwhile, everything else is turned off (including printer). Once octoprint is loaded and I click on the button to turn on my ATX PSU printer (Anet A8) turns on and successfully loads the software (I am using Skynet). However, because the printer was not initialized as an USB device originally (that's my guess) I am unable to connect to it. 
Kindly advise on the issue.

**Comment by kantlivelong** [comment]
[PortLister](http://plugins.octoprint.org/plugins/portlister/) will automatically connect to your printer once the usb serial device becomes available.

**Comment by rplc** [comment]
I just set everything up. If you reload the page the printer is in the menu and you can connect to the printer.

Nethertheless it would be great if the plugin has the option to connect to a printer as soon as the psu-on button is hit.

**Comment by kantlivelong** [comment]
@rplc Does **PortLister** not work for you? I just don't see the need to reinvent the wheel if I don't have to.

**Comment by rplc** [comment]
On the contrary it works great. I'm just missing an option like connect automatically to the printer as soon as it comes online.

**Comment by kantlivelong** [comment]
That's what PortLister does.

**Comment by rplc** [comment]
Okay?! Then it is not working properly on my side. For me it just refreshes the serial port Dropdown Box. I then have to click manually on connect.

**Comment by kantlivelong** [comment]
Do you have auto-connect enabled?

See
https://github.com/markwal/OctoPrint-PortLister

**Comment by rplc** [comment]
My bad...
The autoconnect_delay was set to the standard 20 (seconds). I've never waited 20 seconds...
Just set it to 2 seconds and everything works like a charm.

Sorry for the trouble...

**Comment by kantlivelong** [comment]
No worries. :+1:
