### ISSUE TITLE
Icon botton will not Toggle on or off

### ISSUE THREAD

**Issue by shane84948** [kantlivelong/OctoPrint-PSUControl#30]
The icon button is grayed out. I can click it but nothing changes or happens. I'm using Version 1.3.2 (master branch) and PSU control 0.1.4.

**Comment by kantlivelong** [comment]
- Could you provide DEBUG logs by following these steps:
- - Enable DEBUG logging ( http://docs.octoprint.org/en/master/configuration/logging_yaml.html ) [Use **octoprint.plugins.psucontrol** for the component name]
- - Stop OctoPrint
- - Clear OctoPrint Logs
- - Start OctoPrint
- - Wait a minute or so.
- - Try switching the PSU on/off (Wait 30 seconds or so in between. Physically switch if needed)
- - Attach logs

**Comment by shane84948** [comment]
May sound like a stupid question but where do I find %APPDATA%/OctoPrint.

**Comment by kantlivelong** [comment]
That's the Windows path. You need to do this on your OctoPrint device which I am assuming is not Windows as it's not supported by this plugin.

**Comment by shane84948** [comment]
I have a raspberry pi zero W which is running Octopi and then Im connecting with octoprint through Crome 
 @ Octopi.local.

**Comment by kantlivelong** [comment]
In that case the OctoPrint settings directory is likely located at **/home/pi/.octoprint**

**Comment by shane84948** [comment]
When I do it through Octopi i get this

pi@octopi:~ $ ~/.octoprint/config.yaml
-bash: /home/pi/.octoprint/config.yaml: Permission denied

**Comment by kantlivelong** [comment]
Basic Linux support is really out of scope here.

Take a screenshot of your configuration for PSU Control.

**Comment by shane84948** [comment]
![image](https://cloud.githubusercontent.com/assets/28072304/25928889/f346b9b4-35bb-11e7-87be-b3eaf93f0d4d.png)

**Comment by shane84948** [comment]
![image](https://cloud.githubusercontent.com/assets/28072304/25928899/071b91b2-35bc-11e7-8deb-e80ff05e6f91.png)
 
not sure if you can see it but the button is grayed out.

**Comment by kantlivelong** [comment]
1. On/Off and Sensing can't use the same GPIO pin.
2. Pin 20 is ground ( https://www.element14.com/community/servlet/JiveServlet/previewBody/80667-102-1-338789/GPIO.png )

**Comment by shane84948** [comment]
Thanks and sorry for wasting your time. I was looking at a wrong pin diagram. Now works as advertised.

**Comment by kantlivelong** [comment]
No worries. Glad its working :+1:
