### ISSUE TITLE
Question: Control via App

### ISSUE THREAD

**Issue by rplc** [kantlivelong/OctoPrint-PSUControl#32]
Hi guys,

just wondering if there is a possibility to control the PSU not only via the webinterface but also via an android octoprint control app (like printoid).

In Printoid I can add custom SSH, GCODE and CURL commands. Is there an API I can call for the PSU Control Plugin?

Greetings Alex

**Comment by kantlivelong** [comment]
#21

**Comment by rplc** [comment]
Great thank you very much.

**Comment by kantlivelong** [comment]
No prob
