### ISSUE TITLE
Add togglePSU API Command

### ISSUE THREAD

**Issue by kantlivelong** [kantlivelong/OctoPrint-PSUControl#33]

**Comment by yschroeder** [comment]
Yes, please! I want to build a keypad that issues API commands and I want to have a button that toggles power. Howevery, I nether found a way via the API to get the current PSU status nor is this toggle option available.

**Comment by kantlivelong** [comment]
@yschroeder Yeah status makes sense too.

**Comment by kantlivelong** [comment]
@yschroeder I've added both API commands to the **additional_api_commands** branch if you want to test it out and let me know how it goes.

Added:
- togglePSU - Toggles supply on/off. No return data
- getPSUState - Returns isPSUOn value(0/1) as a JSON.

**Comment by yschroeder** [comment]
Actually, I have no idea how to use a plugin that is not installed via the integrated GUI. Can you give me a hint on where to find this info?

**Comment by xoniq** [comment]
I will try it today. Yesterday mounted a ATX PSU to it, and turning it on and off goes just fine using the lightning icon. Will try it using the API.

**Comment by xoniq** [comment]
I'm testing it remotely, don't know I am doing it wrong.
Is this the right way to call it?

`/api/turnPSUOff`

**Comment by kantlivelong** [comment]
See #21

**Comment by yschroeder** [comment]
I've tested it now. togglePSU works as expected, thanks for that!

However I can't get the `getPSUState` to work. Is it a POST or a GET? Shouldn't it be a GET on `/api/plugin/psucontrol/PSUState` and then return a json object? I tested some variations but can't get the right response back. Please give a hint on how to use this.

**Comment by kantlivelong** [comment]
It should be a POST that returns json data but I haven't tested it as I don't have a working environment at the moment.

**Comment by kantlivelong** [comment]
curl -s -H "Content-Type: application/json" -H "X-Api-Key: **YOUR_API_KEY**" -X POST -d '{ "command":"getPSUState" }' http://**YOUR_OCTOPRINT_SERVER**/api/plugin/psucontrol

**Comment by yschroeder** [comment]
That curl command returns a 500 error.

**Comment by xoniq** [comment]
@yschroeder

Remove plugin and add again via the same url. Yesterday they fixed it in a new commit based on my log. (See the other issue)

**Comment by yschroeder** [comment]
Getting the status works as described for me after installing again.

I would like to see both features getting deployed to release. For now I will keep using the plugin from the zip file.

**Comment by gurusonwheels** [comment]
plugin url does not work . i get 404

**Comment by kantlivelong** [comment]
@gurusonwheels its in devel now.
