### ISSUE TITLE
M80 s 

### ISSUE THREAD

**Issue by broncosis** [kantlivelong/OctoPrint-PSUControl#35]
Marlin has added support for M80 S which gives the status of the power on pin of a board 
this could be used as a alternative to the gpio monitoring

**Comment by kantlivelong** [comment]
It looks like this was added less than a month ago and is only available in Marlin. Will revisit when adoption is greater.

**Comment by broncosis** [comment]
Yup it's new but figured at least put out there on the radar

⁣Sent from BlueMail ​

**Comment by aequitas** [comment]
@broncosis I added a working implementation for this feature, feel free to try it out.

**Comment by broncosis** [comment]
I will thank you very much  
I will let you know in a day or 2

⁣Sent from BlueMail ​

**Comment by spaelectronics** [comment]
Add support for Smoothie also please!

The command: "M1000 switch psu" will return the following string: "switch psu is 1" or "switch psu is 0" if on or off, respectively.

You can see more info here:
http://smoothieware.org/switch#console-command-to-read-a-switch-state

**Comment by VjyedSC0UFMc8z** [comment]
I would like to bump this to support M80 S for sensing as well.

**Comment by kantlivelong** [comment]
This can now be done as a sub-plugin if someone desires. Won't be adding to core. See #49
