### ISSUE TITLE
Invert sense pin

### ISSUE THREAD

**Issue by agreen** [kantlivelong/OctoPrint-PSUControl#36]
I hooked up my PSU sense with an optocoupler, but this has a side effect of inverting the logic for the pin. It would be handy if there was an "Invert" checkbox for the sense pin.  I hooked it up using the internal pullup of the rpi GPIO,

**Comment by agreen** [comment]
I basically have a PR ready to go for this, however I wanted feedback from you. I have to make one assumption to get it to work right... If you're using an optocoupler and inverting the signal (so that ground is on, and "not ground" is off)... You either need to use an external pullup resistor, or enable internal pullup. What's your thought on enabling internal pullup/down depending on invert sense state? I think it might make the code a bit "safer".. and would still work if there was an external pullup/down.

**Comment by kantlivelong** [comment]
I'd personally prefer another option next to the invert checkbox as a dropdown to specify NONE, PUD_UP, PUD_DOWN.

- No Internal Pull-Up/Down
- Internal Pull-Up
- Internal Pull-Down

**Comment by agreen** [comment]
Will do. I'll get that added.  Spent a few hours last night scratching my head as to why it wasn't working before I realized.  Also, it's something that should probably be documented onscreen or somewhere. i.e. 
Suggested values:
not inverted = internal pull-down
inverted = internal pull-up

**Comment by kantlivelong** [comment]
Would likely just update the README.md as it's already a bit dated by now.

**Comment by kantlivelong** [comment]
PR Merged
