### ISSUE TITLE
ability to add another psu / control / CLONE

### ISSUE THREAD

**Issue by nowkillkennys** [kantlivelong/OctoPrint-PSUControl#37]
ability to add another psu / control two power supplies wit this plugin? (add extra button)?

**Comment by kantlivelong** [comment]
Could you provide a use case for this?

**Comment by nowkillkennys** [comment]
I have two psu's one for the heat bed and one for the hotend,board,leds
Definitely heats up a lot faster !

Sent from my iPhone

On 14 Jun 2017, at 2:27 pm, Shawn Bruce <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you provide a use case for this?

**Comment by kantlivelong** [comment]
Couldn't you just wire the ON/OFF pin to both PSUs then use an AND gate to determine if both are on for sensing?

**Comment by nowkillkennys** [comment]
i use psu control to trigger a relay (for psu1) and i want todo the same for (psu2) via the 2nd switch

**Comment by kantlivelong** [comment]
But what exactly is the use case for having separate toggles? Both PSUs should be on while printing and the controller would toggle switching on the bed itself.

I don't think this is something I would pursue adding unless there is enough demand for it. For now you could simply clone the plugin and replace  **psucontrol** with **psucontrol2**.

**Comment by nowkillkennys** [comment]
how?

**Comment by kantlivelong** [comment]
how what?

**Comment by nowkillkennys** [comment]
how do i clone the plug in

**Comment by kantlivelong** [comment]
You'll have to download the source, make the changes, and finally upload it to OctoPrint. 

http://docs.octoprint.org/en/master/plugins/

**Comment by nowkillkennys** [comment]
i havent a clue how todo all that oh well back to the drawing board thanks for the fast reply

**Comment by nowkillkennys** [comment]
i have no programing history anyone want to make a clone of this?
