### ISSUE TITLE
Add a second relay signal

### ISSUE THREAD

**Issue by leobel96** [kantlivelong/OctoPrint-PSUControl#42]
Could you add the possibility to switch on two relay instead of only one? This is useful to, for example, switch on a led strip with the printer. Thank you.

**Comment by kantlivelong** [comment]
It's funny you ask. A few days ago I wanted the same thing and ended up stripping the plugin down and making another simple one just for lights. I'll post it in a few.

**Comment by kantlivelong** [comment]
https://github.com/kantlivelong/OctoPrint-LightControl

**Comment by leobel96** [comment]
What a coincidence ahahah. Thank you. Will it be integrated with PSU control so that with only a switch you can switch on/off them together? Or you will need to act on them separately? When should it be released? Thank you again :)

**Comment by kantlivelong** [comment]
No plans on integrating into PSU Control as it's a bit out of scope. Not really intending on releasing Light Control but I use it on mine without issue. Just install the plugin with the zip.

**Comment by leobel96** [comment]
Ok. Bye bye.
