### ISSUE TITLE
Add M106 to default Triggers

### ISSUE THREAD

**Issue by blindMoe** [kantlivelong/OctoPrint-PSUControl#45]
M106 needs to be added to the trigger commands for turning on the PSU.  Mine wasn't turning on and it lead to thermal runaways since the bed would not actually heat up when starting a print.  I ended up having to use the lightning bold icon to turn on the PSU before starting a print.

**Comment by kantlivelong** [comment]
Agreed

**Comment by kantlivelong** [comment]
Available in devel. Closing
