### ISSUE TITLE
Remove Pi(RPi.GPIO) requirement

### ISSUE THREAD

**Issue by kantlivelong** [kantlivelong/OctoPrint-PSUControl#51]
Remove the RPi.GPIO requirement but disable features if not a Pi.

**Comment by kantlivelong** [comment]
This is now available in the **[remove_rpi_gpio_requirement](https://github.com/kantlivelong/OctoPrint-PSUControl/tree/remove_rpi_gpio_requirement)** branch.

Looking for testers.

**Comment by JoblyFonty** [comment]
Works for me. :thumbsup:

**Comment by kantlivelong** [comment]
@JoblyFonty If using a device other than a Pi would you be able to tell me if the GPIO  options in the **Switching** and **Sensing** drop downs is removed?

**Comment by JoblyFonty** [comment]
No, they are present. But I have got RPi.GPIO installed in the venv even though it does not work. So that would explain that.

**Comment by kantlivelong** [comment]
I was just looking at this about 10 minutes ago and I think I see/have fixed the problem. Even though RPi.GPIO throws an import error on non-Pi devices it will still be listed in sys.modules. I tested it out here and it seems okay. Mind trying with the latest?

**Comment by kantlivelong** [comment]
Merged in devel
