### ISSUE TITLE
doesn't power PSU (wainting for heaters)

### ISSUE THREAD

**Issue by albebert** [kantlivelong/OctoPrint-PSUControl#52]
Hello, i've an issue with your plugin.

i've setup auto poweroff with an idle timeout at 5min and wait for temperature 150°c. 

but the plugin can't shutdown psu.

in log : 

octoprint.plugins.psucontrol - INFO - Waiting for heaters(tool0) before shutting off PSU...

but temp is below 150°c (if i setup 190°c it works, it's my printing temp). 

can you help me ? thanks

**Comment by kantlivelong** [comment]
#31 ?
