### ISSUE TITLE
Automatic PSU OFF doesn't work unless connected to server

### ISSUE THREAD

**Issue by Jamackey** [kantlivelong/OctoPrint-PSUControl#60]
As soon as I connect back to a server, the Relay switches off.

**Comment by kantlivelong** [comment]
- What settings are you using?
- Can you provide DEBUG logs?

**Comment by Jamackey** [comment]
Current Settings:
![image](https://user-images.githubusercontent.com/31521142/30229259-1509dd7a-94d9-11e7-8777-a54bdca67a5d.png)
![image](https://user-images.githubusercontent.com/31521142/30229283-2a0af1f0-94d9-11e7-86e3-81ffcdf87883.png)

How can I find the debug logs?

**Comment by kantlivelong** [comment]
Could you provide DEBUG logs by following these steps:
- Enable DEBUG logging ( http://docs.octoprint.org/en/master/configuration/logging_yaml.html ) [Use **octoprint.plugins.psucontrol** for the component name]
- Stop OctoPrint
- Clear OctoPrint Logs
- Start OctoPrint
- Wait a minute or so.
- Recreate issue
- Attach logs

**Comment by kantlivelong** [comment]
Hello,

Is this still an issue?

**Comment by kantlivelong** [comment]
Closing. Re-open if this is still an issue.
