### ISSUE TITLE
Add beforePSUOff & afterPSUOn GCode scripts

### ISSUE THREAD

**Issue by kantlivelong** [kantlivelong/OctoPrint-PSUControl#64]
Add a **beforePSUOff** and **afterPSUOn** GCode scripts.

Scripts should be located in {BASEDIR}/scripts/gcode/psucontrol/ and should be editable in similar fashion to the built-in **GCODE Scripts**

**Comment by apprentice10** [comment]
I'm going to bump this post since I'm running Klipper, After the power is up you should run a "FIRMWARE_RESTART" command to be able to print.

**Comment by kantlivelong** [comment]
This is in 0.1.10

**Comment by CharlieTemplar** [comment]
> I'm going to bump this post since I'm running Klipper, After the power is up you should run a "FIRMWARE_RESTART" command to be able to print.

Is there anything that klipper needs before powerOff?  and does it need post On delay before FIRMWARE_RESTART?
