### ISSUE TITLE
Timeout after PSU on to auto-connect to printer.

### ISSUE THREAD

**Issue by posicat** [kantlivelong/OctoPrint-PSUControl#67]
I end up clicking the connect button too early each time, and confuse OctoPrint it would be great if I could click the power button and have an on-screen countdown (with a delay I would set) and then have it attempt to connect to the printer automatically.

**Comment by kantlivelong** [comment]
If you have a printer controller that uses USB then the PortLister plugin
should do just what you sre looking for.

-- 

-Shawn

**Comment by posicat** [comment]
Just tried it, it works perfectly, thank you!
