### ISSUE TITLE
PSU Control is not ACL aware

### ISSUE THREAD

**Issue by synman** [kantlivelong/OctoPrint-PSUControl#7]
I discovered by happen chance today that PSU Control is not protected by any authentication / authorization scheme provided by OctoPrint.

This means that if your server is accessible to the outside world and you have PSU Control installed that an anonymous user can power on/off your printer.  This presents a significant challenge for internet connected instances of OctoPrint that rely on authentication to gain administrative access to OctoPrint and its plugins.

<img width="251" alt="screen shot 2017-02-09 at 6 34 21 pm" src="https://cloud.githubusercontent.com/assets/1299716/22807737/72a0411a-eef6-11e6-91fc-c7977eb70c5c.png">

**Comment by kantlivelong** [comment]
Looks like it's more of a UI issue as the server does in fact reject the request to turn on/off if not authenticated.

Fixed in https://github.com/kantlivelong/OctoPrint-PSUControl/tree/issue-7. Will be merged to master when ready.

**Comment by synman** [comment]
nice... thank you for the follow up and aesthetic fix.  it caught my eye last night while I was in the middle of print.

**Comment by kantlivelong** [comment]
Fixed in 9c10364e6ae0b0b3e63a543331fe11176db257e9

**Comment by synman** [comment]
thanks for the quick fix
