### ISSUE TITLE
Indicator Icon

### ISSUE THREAD

**Issue by MarioP73** [kantlivelong/OctoPrint-PSUControl#70]
I installed the "PSU Control" plugin and also included a clone of which is called "LED Control" and the lighting switches. Works perfect. I would like to have a different symbol in the head to control, since two flashes are very confusing. But I could not find any reference to the symbol in your code.

How can I include a different symbol?

![img_20171020_152252](https://user-images.githubusercontent.com/29842931/31823184-82d010f2-b5ab-11e7-990c-42dfe5625fd3.JPG)
![img_20171020_152351](https://user-images.githubusercontent.com/29842931/31823192-890ea1d6-b5ab-11e7-93b6-ff1763a604a2.JPG)

Mario

**Comment by kantlivelong** [comment]
Fork the plugin and modify it. Alternatively if you are simply turning the LEDs on/off see https://github.com/kantlivelong/OctoPrint-LightControl. It uses a lightbulb indicator icon.

**Comment by MarioP73** [comment]
The LightControl has unfortunately not the functions like the PSU, however a nice symbol. The Invert of the GPIO unfortunately does not work with the LightControl. Both presets result in the same result. Would a full version of the LightControl like the PSU possible?

Mario
![img_20171020_161218](https://user-images.githubusercontent.com/29842931/31825372-5a754788-b5b2-11e7-85da-f1d859d58b88.JPG)

**Comment by kantlivelong** [comment]
I have no plans to make any changes to LightControl. I made it for my own use and shared it if other want it. In my opinion I would ask the dev of LEDControl to use the lightbulb icon.

**Comment by MarioP73** [comment]
LED control is actually by you. I have adapted the code so that a new plugin has emerged. This allowed me to install PSU and LED in parallel. The references in the LED Control are even yours. The changes I made by an editor, which has replaced all characters with "PSU" and "psu" against "LED" / "led".

Mario

**Comment by kantlivelong** [comment]
I noticed as I typed that. You should be able to fork LightControl and add the invert option fairly easily.
