### ISSUE TITLE
Use class instead of direct element color override for nav icon state

### ISSUE THREAD

**Issue by chron0** [kantlivelong/OctoPrint-PSUControl#73]
Currently the icon gets a direct element color override of color: rgb(0, 255, 0);
That interferes with other themes efforts to keep a consistent color matching scheme.

Could we use an "active" class, which can be overridden by themes?

**Comment by kantlivelong** [comment]
I've committed this to a new branch. Would anyone be willing to give it a test?

**Comment by chron0** [comment]
Sure, if no one else beats me to it, I'll try it the coming weekend.

**Comment by kantlivelong** [comment]
I tested this with a modified TouchUI (PR pending) and it looks good here. Will merge into devel soon.

**Comment by kantlivelong** [comment]
Tested again with modified Cyborg theme. Merged into devel.
