### ISSUE TITLE
PSU Control does not play nicely with TouchUI

### ISSUE THREAD

**Issue by synman** [kantlivelong/OctoPrint-PSUControl#8]
I'll likely open this as an issue in the TouchUI repo as well but there is currently a problem between TouchUI and PSU Control.  When on a low density touchscreen (3.5 LCD attached to the Pi) with PSU Control and TouchUI active when you try to open the System/Settings/Logon spanner (see attached) the entire context menu is blanked out.

You can also simulate this fairly easily by just shrinking your browser's width (see attached).

<img width="406" alt="screen shot 2017-02-10 at 6 02 16 pm" src="https://cloud.githubusercontent.com/assets/1299716/22847500/399daff4-efbb-11e6-9482-1ecffb47341b.png">

**Comment by synman** [comment]
And tying back to TouchUI issue:

https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/97

**Comment by synman** [comment]
here you can see what is going on:

<img width="904" alt="screen shot 2017-02-10 at 6 20 20 pm" src="https://cloud.githubusercontent.com/assets/1299716/22847819/b088a07c-efbd-11e6-8e72-e0c0dae5876b.png">

**Comment by kantlivelong** [comment]
Fixed in TouchUI - https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/97
