### ISSUE TITLE
Request -  switch LEDS on and off?? 

### ISSUE THREAD

**Issue by chilternflyer** [kantlivelong/OctoPrint-PSUControl#94]
I'm using your plug in to switch some LEDS on and off instead of the PSU.
I've got an Original Prusa i3 MK3. I doesn't respond to an M42 command and to be honest has no expansion pins on the Einsy board anyway so your plug has been very useful.

Would it be possible to expand it to drive three or four GPIO pins using the M42 command? Then I can use RGB LEDS ;-)

**Comment by kantlivelong** [comment]
Sorry but won't do.

Perhaps this plugin would work for you:
https://plugins.octoprint.org/plugins/ledstripcontrol/
