### ISSUE TITLE
Powering Raspberry Pi from PSU

### ISSUE THREAD

**Issue by StudioKamar** [kantlivelong/OctoPrint-PSUControl#99]
I have question about powering RPI from stand by power from ATX power supply. Can i do that and then after ATX PSU is turned on give the RPI second +5v from ATX not a STBY +5v but normal 5v ?? I think my RPI is underpovered using only STBY

**Comment by kantlivelong** [comment]
You can certainly do that by using two diodes but I would check to see how much current is actually being drawn and how much the PSU can actually handle.

5V         -> Diode - \
                              -> Pi
5VSB    -> Diode  -/
